server:
  name: "survival"
  type: "NEOFORGE"
  version: "1.21.1"
  neoforgeVersion: "latest"
  memory: "16G"
  memoryRequest: "16Gi"
  memoryLimit: "16Gi"
  cpuRequest: "2000m"
  cpuLimit: "2000m"
  jvmOpts: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20"
  onlineMode: "FALSE"
  mods:
    - "yungs-api"
    - "terrablender"
    - "architectury-api"
    - "geckolib"
    - "yungs-better-nether-fortresses"
    - "yungs-better-dungeons"
    - "yungs-better-jungle-temples"
    - "yungs-better-ocean-monuments"
    - "yungs-better-mineshafts"
    - "yungs-better-end-island"
    - "yungs-better-strongholds"
    - "yungs-better-witch-huts"
    - "yungs-better-desert-temples"
    - "yungs-extras"
    - "yungs-better-caves"
    - "yungs-cave-biomes"
    - "farmers-delight"
    - "sophisticated-backpacks"
    - "sophisticated-core"
    - "waystones"
    - "handcrafted"
    - "resourceful-lib"
    - "chipped"
    - "torchmaster"
    - "aquaculture"
    - "aquaculture-delight"
    - "ends-delight"
    - "expanded-delight"
    - "my-nethers-delight"
    - "more-delight"
    - "brewin-and-chewin"
    - "crabbers-delight"
    - "rustic-delight"
    - "trailtales-delight"
    - "cultural-delights"
  extraEnv:
    - name: MODRINTH_ALLOWED_VERSION_TYPE
      value: "alpha"
    - name: MODRINTH_DOWNLOAD_DEPENDENCIES
      value: "REQUIRED"
    - name: CF_PROJECTS
      value: "306345,246763" # TerraBlender, GeckoLib (Already on client/server mostly)
    - name: MODS
      value: "https://www.curseforge.com/api/v1/mods/227639/files/7797302/download"
    - name: CF_DOWNLOAD_DEPENDENCIES
      value: "REQUIRED"
    - name: CF_ALLOWED_VERSION_TYPE
      value: "alpha"

network:
  nodePort: 30065
  serviceType: "NodePort"
  port: 25565

storage:
  size: "20Gi"

metrics:
  enabled: true
  port: 8080

velocity:
  enabled: true
