server:
  name: "mod"
  type: "NEOFORGE"
  version: "1.21.1"
  neoforgeVersion: "latest"
  memory: "30G"
  memoryRequest: "30Gi"
  memoryLimit: "30Gi"
  cpuRequest: "4000m"
  cpuLimit: "4000m"
  jvmOpts: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:+UnlockExperimentalVMOptions -XX:G1MixedGCCountTarget=4 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40"
  onlineMode: "FALSE"
  mods:
    - "mekanism"
    - "mekanism-additions"
    - "mekanism-generators"
    - "mekanism-tools"
    - "trash-cans"
    - "ae2"
    - "applied-energistics-2-wireless-terminals"
    - "applied-mekanistics"
    - "cc-tweaked"
    - "botany-pots"
    - "botany-trees"
    - "mekanismmoremachine"
    - "mekanism-lasers"
    - "mekanismmoremodules"
    - "mekanism_extra"
    - "evolved-mekanism"
    - "classicperipherals"
  extraEnv:
    - name: MODRINTH_ALLOWED_VERSION_TYPE
      value: "alpha"
    - name: MODRINTH_DOWNLOAD_DEPENDENCIES
      value: "REQUIRED"
    - name: CF_PROJECTS
      value: "543592" # Mekanism Turrets
    - name: CF_DOWNLOAD_DEPENDENCIES
      value: "REQUIRED"
    - name: CF_ALLOWED_VERSION_TYPE
      value: "alpha"

network:
  nodePort: 30066
  serviceType: "NodePort"
  port: 25565

storage:
  size: "30Gi"

metrics:
  enabled: true
  port: 8080

velocity:
  enabled: true
