{
 "title": "GKE Resource Map",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(container_cpu_usage_seconds_total{location=\"gke\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\", location=\"gke\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "GKE Total Cluster Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster overall CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", location=\"gke\"}[5m]))",
     "legendFormat": "Total CPU Cores"
    }
   ]
  },
  {
   "title": "Cluster overall Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\", location=\"gke\", id=\"/\"}) / (4*1024*1024*1024)",
     "legendFormat": "Total Memory %"
    }
   ]
  },
  { "title": "Per-Pod Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pod CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\", pod=~\"^$pod$\", container!=\"\", location=\"gke\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"^$namespace$\", pod=~\"^$pod$\", container!=\"\", location=\"gke\"}) by (pod) / (4*1024*1024*1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}