apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-sa
  namespace: monitoring-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-cluster-role
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "apps"]
    resources:
      - deployments
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vm-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: vm-sa
    namespace: monitoring-prometheus
roleRef:
  kind: ClusterRole
  name: vm-cluster-role
  apiGroup: rbac.authorization.k8s.io
