apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Values.server.name }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: minecraft-java
    app.kubernetes.io/component: {{ .Values.server.name }}
    app.kubernetes.io/managed-by: helm
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.storage.size }}
