apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gw-config
  namespace: minecraft
  labels:
    app.kubernetes.io/name: "nginx"
    app.kubernetes.io/component: "gateway"
    app.kubernetes.io/managed-by: "kubectl"
    env: "prod"
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /dev/stdout warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    stream {
        # GKE kube-dns resolver
        resolver 10.102.0.10 valid=10s;

        log_format basic '$remote_addr [$time_local] '
                         '$protocol $status $bytes_sent $bytes_received '
                         '$session_time "$upstream_addr"';

        access_log /dev/stdout basic;

        # Java Edition (Velocity on GKE)
        server {
            listen 25565;
            set $velocity_backend velocity.minecraft.svc.cluster.local:25577;
            proxy_pass $velocity_backend;
            proxy_timeout 10m;
            proxy_connect_timeout 30s;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gw
  namespace: minecraft
  labels:
    app.kubernetes.io/name: "nginx"
    app.kubernetes.io/component: "gateway"
    app.kubernetes.io/managed-by: "kubectl"
    env: "prod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gw
  template:
    metadata:
      labels:
        app: nginx-gw
    spec:
      serviceAccountName: tailscale-sa
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 25565
              name: minecraft
              protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "5m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

      volumes:
        - name: config
          configMap:
            name: nginx-gw-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gw-java
  namespace: minecraft
  labels:
    app.kubernetes.io/name: "nginx"
    app.kubernetes.io/component: "gateway"
    app.kubernetes.io/managed-by: "kubectl"
    env: "prod"
spec:
  type: LoadBalancer
  loadBalancerIP: 35.200.78.252  # tagomori-minecraft-ip（静的IP）
  externalTrafficPolicy: Cluster
  selector:
    app: nginx-gw
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      protocol: TCP
