# On-Premises Bedrock UDP Service via Direct Routing
apiVersion: v1
kind: Service
metadata:
  name: onprem-bedrock-udp
  namespace: minecraft
spec:
  type: ExternalName
  externalName: 100.107.122.45
---
# On-Premises Survival TCP Service via Direct Routing
apiVersion: v1
kind: Service
metadata:
  name: onprem-survival-tcp
  namespace: minecraft
spec:
  type: ExternalName
  externalName: 10.43.153.44
---
# On-Premises MOD TCP Service via Direct Routing
apiVersion: v1
kind: Service
metadata:
  name: onprem-mod-tcp
  namespace: minecraft
spec:
  type: ExternalName
  externalName: 10.43.224.226
