apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-scraper
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-scraper-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kubelet-api-admin
subjects:
  - kind: ServiceAccount
    name: metrics-scraper
    namespace: kube-system
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: metrics-scraper-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "metrics-scraper"
