apiVersion: v1
kind: ConfigMap
metadata:
  name: waterdogpe-config
  namespace: minecraft
data:
  config.yml: |
    listener:
      motd: "§bsushiski §3Bedrock"
      host: 0.0.0.0:19132
      max_players: 20

    servers:
      bedrock-survival:
        address: "100.69.90.93:19132"
        public_address: "100.69.90.93:19132"
        server_type: bedrock

    priorities:
      - bedrock-survival

    online_mode: true
    use_fast_codec: true
    use_login_extras: true
    prefer_fast_transfer: true
    upstream_compression_level: 2
    downstream_compression_level: 6
    enable_ipv6: false
    enable_query: true
    default_idle_threads: -1
